language: node_js
node_js:
  - 8.9.1
cache:
  directories:
    - "node_modules"

jobs:
  include:
    - stage: Lint
      script: npm run lint
    - stage: Test
      script: npm run test
    - stage: npm release
      deploy:
        provider: npm
        api_key: $NPM_API_KEY
        on: deploy-npm-release