sudo: required

services:
  - docker

before_script:
  - docker build -t adriantombu/array-shuffle:dev .

script:
  - docker run adriantombu/array-shuffle:dev yarn lint
  - docker run adriantombu/array-shuffle:dev yarn test

before_deploy:
  - docker run --name array_shuffle adriantombu/array-shuffle:dev
  - docker cp array_shuffle:usr/app/lib .

deploy:
  skip_cleanup: true
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_API_KEY
  on:
    branch: master
